### ISSUE TITLE
 Something wrong! Cannot set the calendar date

### ISSUE THREAD

**Issue by xiaoqiang2005** [anhtuanbw/calendar-plugin#1]
http://intest.life.cntaiping.com/coverage/s1/res/product/4040/insuconfig.html

The date space on this website is unusable. Is there a way to update it?

**Comment by xiaoqiang2005** [comment]
> http://intest.life.cntaiping.com/coverage/s1/res/product/4040/insuconfig.html
> 
> 本网站上的日期空间无法使用。有没有办法更新它？
If you see the question，can you  answer to me

**Comment by anhtuanbw** [comment]
hi @xiaoqiang2005, thank for reporting this issue.
Currently, my keyword doesn't support for your calendar type. 
It only supports the calendar type below:
![image](https://user-images.githubusercontent.com/9160682/56572408-34417080-65e9-11e9-89ac-406e47608cfd.png)
(Image from agoda.com)

However, I'll create a new keyword for your calendar type. I will let you know when I have done my work.

Thanks.

**Comment by xiaoqiang2005** [comment]
> hi @xiaoqiang2005, thank for reporting this issue.
> Currently, my keyword doesn't support for your calendar type.
> It only supports the calendar type below:
> ![image](https://user-images.githubusercontent.com/9160682/56572408-34417080-65e9-11e9-89ac-406e47608cfd.png)
> (Image from agoda.com)
> 
> However, I'll create a new keyword for your calendar type. I will let you know when I have done my work.
> 
> Thanks.

ok！Thank you for your reply。
