### ISSUE TITLE
new calendar

### ISSUE THREAD

**Issue by HansimGlueck1234** [anhtuanbw/calendar-plugin#3]
Hi,
thank you very much for developing this plugin ;-)

I have some trouble getting it to work with this calendar:
https://www.nh-hotels.com/b2b-ccg/84d28ba8772bf6fe610060b92eba4cf9

- Hans

**Comment by anhtuanbw** [comment]
Hi @HansimGlueck1234,
Thanks for reporting this issue. I am working on an update to support your calendar.
It will be done in a couple of days.

**Comment by anhtuanbw** [comment]
Hi,
I release new version to support your calendar type.
Please reload the plugin on Katalon Studio to get the latest version of plugin. 

New version: 1.0.3

Thanks.

**Comment by anhtuanbw** [comment]
Close this issue. 
If it works on your calendar, please help to rate and review my plugin https://store.katalon.com/product/25/Calendar-Keywords#rating-content ;)
